management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    com.wokoworks: debug
  pattern:
    console: "%date{yy-MM-dd HH:mm:ss.SSS} %5p ${PID:-} --- [%15.15t] %-40.40logger{39}[%4line]: %msg%n"

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dec_service_chain_tron_testnet?cachePrepStmts=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      name: dec_service_chain_ethereum
      initial-size: 0
      min-idle: 3
      max-active: 50
      max-wait: 60000
      test-on-borrow: false
      test-while-idle: true
      validation-query: SELECT 1
      poolPreparedStatements: true
      max-pool-prepared-statement-per-connection-size: 100
  rabbitmq:
    #    ssl:
    #      enabled: true
    #    host: b-523bef95-91fa-49e6-a7b8-1fa971496efa.mq.us-east-1.amazonaws.com
    #    port: 5671
    #    username: rabbitmq
    #    password: XUhfPSJxsqGL
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    #  支持发布确认
    publisher-confirms: true
    #  支持发布返回
    publisher-returns: true
    listener:
      simple:
        #  采用手动应答
        acknowledge-mode: auto
        #  当前监听容器数
        concurrency: 1
        #  最大数
        max-concurrency: 2
        #  是否支持重试
        retry:
          enabled: true

dec-chain-tron-schedule:
  schedule-system: "dec-middleware-schedule"
  #public key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANPKRvcPQXNSDV+rvaHu9H46pAQwdIlienOx9ZUAKWciXcMw+tlFQF30ACStYXrJHev+SGnbh9076FAUQ82zdu0CAwEAAQ==
  pri-key: "MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEA08pG9w9Bc1INX6u9oe70fjqkBDB0iWJ6c7H1lQApZyJdwzD62UVAXfQAJK1heskd6/5IaduH3TvoUBRDzbN27QIDAQABAkEAnbS1LUmF4jqKTOBU4B1QoCJIefoe/SKArmAoz+AD9JAO19Zb3eE8Dmy002RrsxsOZ+IeJuEU6iBaugiaSILdvQIhAOtFEAVpb7/OJKazIyB5PzlaIdlzUQnu2t2QkCiTehLbAiEA5nOWwS1PwXmZuxaU+dFc0CSZUuXnxLoxR6D2eo8EM9cCIQCXP6rxD7t7v3bohDmM4uW2ZS9lsDDlBd1Gm21R6J2OCQIgGDMXJ538fBKq5AyRBFLJ7kmJmDzwQ6ZRunXarDAMfu0CIDI28EQAMmG6BwbN8aYLzfezzlUN7OldQ+PIanF3OCNW"

chain:
  code: "tron-testnet"
  chain-id: 27
  rpc-list:
    - "127.0.0.1:50051"
  # 定时任务
  retry-count: 10
  delete-days: 10


ribbon.ReadTimeout: 60000
ribbon.ConnectTimeout: 60000